name: Build Nightly
on:
  push: # TODO: remove this, only for debugging....
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  nightly:
    name: Build Nightly
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: clean install dependencies
        run: npm ci    
      
      - name: compile and create vsix
        run: npm run package -o extension-nightly.vsix

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: vscode-terraform-nightly-${{github.sha}}.vsix
          path: ${{github.workspace}}/extension-nightly.vsix
